just

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -103,7 +103,7 @@ jobs:
       - name: Create Builder
         run: |
           for i in {1..5}; do
-            pack builder create ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/java-fckfips-builder-stack:1.0.0 \
+            pack builder create ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/java-fckfips-builder-stack-amd64:1.0.0 \
               --config ./2-builder/builder.toml \
               --target linux/amd64 \
               --publish  && break || {
@@ -111,7 +111,15 @@ jobs:
                 sleep 15
               }
           done
-          docker image ls
+          for i in {1..5}; do
+            pack builder create ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/java-fckfips-builder-stack-arm64:1.0.0 \
+              --config ./2-builder/builder.toml \
+              --target linux/arm64 \
+              --publish  && break || {
+                echo "Builder creation failed due to GHCR lag, retrying in 15s... (Attempt $i/5)"
+                sleep 15
+              }
+          done
 
 
   #     - id: resolve-digests
